#spring.application.name=baseball
#spring.datasource.url=jdbc:mysql://localhost:3306/baseball
#spring.datasource.username=root
#spring.datasource.password=Junpei74
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${JAWSDB_URL}
spring.datasource.username=d185b6zttxy02ofx
spring.datasource.password=h8ztf49alkt3fk89
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
